%128x128.png: svg/%.svg
	convert -background transparent -scale 128x128 $< $@
%128x128.gif: svg/%.svg
	convert -background transparent -scale 128x128 $< $@
%64x64.png: svg/%.svg
	convert -background transparent -scale 64x64 $< $@
%64x64.gif: svg/%.svg
	convert -background transparent -scale 64x64 $< $@
%50x50.png: svg/%.svg
	convert -background transparent -scale 50x50 $< $@
%50x50.gif: svg/%.svg
	convert -background transparent -scale 50x50 $< $@
%40x40.png: svg/%.svg
	convert -background transparent -scale 40x40 $< $@
%40x40.gif: svg/%.svg
	convert -background transparent -scale 40x40 $< $@
%32x32.png: svg/%.svg
	convert -background transparent -scale 32x32 $< $@
%32x32.gif: svg/%.svg
	convert -background transparent -scale 32x32 $< $@
%24x24.png: svg/%.svg
	convert -background transparent -scale 24x24 $< $@
%24x24.gif: svg/%.svg
	convert -background transparent -scale 24x24 $< $@
%16x16.png: svg/%.svg
	convert -background transparent -scale 16x16 $< $@
%16x16.gif: svg/%.svg
	convert -background transparent -scale 16x16 $< $@
%12x12.png: svg/%.svg
	convert -background transparent -scale 8x8 $< $@
%12x12.gif: svg/%.svg
	convert -background transparent -scale 8x8 $< $@
%8x8.png: svg/%.svg
	convert -background transparent -scale 8x8 $< $@
%8x8.gif: svg/%.svg
	convert -background transparent -scale 8x8 $< $@

sbwedge: sbwedge8x8.png sbwedge12x12.png sbwedge16x16.png sbwedge24x24.png \
	 sbwedge32x32.png sbwedge40x40.png sbwedge50x50.png sbwedge64x64.png \
	 sbwedge8x8.gif sbwedge12x12.gif sbwedge16x16.gif sbwedge24x24.gif \
	 sbwedge32x32.gif sbwedge40x40.gif sbwedge50x50.gif sbwedge64x64.gif
tagicon: TagIcon8x8.png TagIcon12x12.png TagIcon16x16.png TagIcon24x24.png \
	 TagIcon32x32.png TagIcon40x40.png TagIcon50x50.png TagIcon64x64.png \
	 TagIcon8x8.gif TagIcon12x12.gif TagIcon16x16.gif TagIcon24x24.gif \
	 TagIcon32x32.gif TagIcon40x40.gif TagIcon50x50.gif TagIcon64x64.gif
diaglink: DiagLink8x8.png DiagLink12x12.png DiagLink16x16.png DiagLink24x24.png \
	DiagLink32x32.png DiagLink40x40.png DiagLink50x50.png DiagLink64x64.png \
	DiagLink8x8.gif DiagLink12x12.gif DiagLink16x16.gif DiagLink24x24.gif \
	DiagLink32x32.gif DiagLink40x40.gif DiagLink50x50.gif DiagLink64x64.gif
compass: CompassIcon8x8.png CompassIcon12x12.png CompassIcon16x16.png CompassIcon24x24.png \
	CompassIcon32x32.png CompassIcon40x40.png CompassIcon50x50.png CompassIcon64x64.png \
	CompassIcon8x8.gif CompassIcon12x12.gif CompassIcon16x16.gif CompassIcon24x24.gif \
	CompassIcon32x32.gif CompassIcon40x40.gif CompassIcon50x50.gif CompassIcon64x64.gif


